/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ScholarshipApplicationListRelationFilter } from "../../scholarshipApplication/base/ScholarshipApplicationListRelationFilter";
import { ScholarshipProviderWhereUniqueInput } from "../../scholarshipProvider/base/ScholarshipProviderWhereUniqueInput";

@InputType()
class ScholarshipWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isPublished?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ScholarshipApplicationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScholarshipApplicationListRelationFilter)
  @IsOptional()
  @Field(() => ScholarshipApplicationListRelationFilter, {
    nullable: true,
  })
  scholarshipApplications?: ScholarshipApplicationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScholarshipProviderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ScholarshipProviderWhereUniqueInput)
  @IsOptional()
  @Field(() => ScholarshipProviderWhereUniqueInput, {
    nullable: true,
  })
  scholarshipProvider?: ScholarshipProviderWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  shortlistingStage?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { ScholarshipWhereInput as ScholarshipWhereInput };
