/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { EnumStudentKycStatus } from "./EnumStudentKycStatus";
import { ScholarshipApplicationListRelationFilter } from "../../scholarshipApplication/base/ScholarshipApplicationListRelationFilter";

@InputType()
class StudentWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  kycDetails?: JsonFilter;

  @ApiProperty({
    required: false,
    enum: EnumStudentKycStatus,
  })
  @IsEnum(EnumStudentKycStatus)
  @IsOptional()
  @Field(() => EnumStudentKycStatus, {
    nullable: true,
  })
  kycStatus?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ScholarshipApplicationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScholarshipApplicationListRelationFilter)
  @IsOptional()
  @Field(() => ScholarshipApplicationListRelationFilter, {
    nullable: true,
  })
  scholarshipApplications?: ScholarshipApplicationListRelationFilter;
}

export { StudentWhereInput as StudentWhereInput };
